apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: invoice-app
commonLabels:
  app: invoice-app 
  instance: base
resources:
- namespace.yaml
- limitrange.yaml
- deployment.yaml
- service.yaml
images:
- name: main
  newName: karasze/invoice-app
  newTag: latest
