apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-provider
  labels:
    tier: frontend
spec:
  replicas: 3
  strategy:
    type: RollingUpdate ## Ramped rollout
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: $APP
      instance: $INSTANCE
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: main
        image: karasze/payment-provider:latest
        imagePullPolicy: IfNotPresent
