apiVersion: v1
kind: Service
metadata:
  name: invoice-app-loadbalander
  labels:
    app: invoice-app
    tier: frontend
spec:
  selector:
    app: invoice-app
  ports:
    - port: 8081
      targetPort: 8081
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-app
  labels:
    app: invoice-app
    tier: frontend
spec:
  replicas: 3
  strategy:
    type: RollingUpdate ## Ramped rollout
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: invoice-app
  template:
    metadata:
      labels:
        app: invoice-app
        tier: frontend
    spec:
      containers:
      - name: main
        image: karasze/invoice-app:latest
        ## This is how you can specify the resources / container
        ## We will use LimitRange on the cluster / namespace level
        #resources:
        #  requests:
        #    cpu: 100m
        #    memory: 100Mi
        #  limits:
        #    cpu: 150m
        #    memory: 150Mi
        imagePullPolicy: IfNotPresent
