apiVersion: v1
kind: Service
metadata:
  name: invoice-app-loadbalander
  labels:
    app: invoice-app
    instance: $INSTANCE
    tier: frontend
spec:
  selector:
    app: invoice-app
    instance: $INSTANCE
  ports:
    - port: 8081
      targetPort: 8081
  type: LoadBalancer
